### ISSUE TITLE
Не хватает сенсоров.

### ISSUE THREAD

**Issue by man55** [dentra/esphome-tion#14]
В интеграции отсутсвует сенсор скорости вентилятора. Из-за этого невозможно посмотреть историю скорости вентилятора.
Можно его добавить?

Так же не хватает сенсоров состония заслонки и состояния работы нагревателя.

<img width="390" alt="Screenshot 2024-01-17 112349" src="https://github.com/dentra/esphome-tion/assets/30772900/15bca127-e2a6-433a-8dac-23a3e55450ef">
<img width="253" alt="Screenshot 2024-01-17 112340" src="https://github.com/dentra/esphome-tion/assets/30772900/32633b51-5e03-4d2d-9bab-9088aaab3a05">

**Comment by dentra** [comment]
Сенсор скорости вентилятора можно сделать самостоятельно, пример чуть позже приведу.

Состояние работы обогревателя видно в истории климата. Или надо как-то по другому?

Air Intake - это и есть состояние заслонки

**Comment by man55** [comment]
В истории вижу только две температуры: таргет и текущую. Поэтому сложно понять что происходило с бризером последние сутки, был ли включен обогреватель или нет, если да, то в какой период. Так же не видно на какой скорости он работал в какое время.
Очень сложно сделать автоматизацию и проверить её работу из-за отсутсвия таких элементарных сенсоров.

**Comment by dentra** [comment]
добавьте в свой конфиг:

```yaml
climate:
  - platform: tion_3s
    id: !extend tion_climate
...
    on_state:
      - lambda: "id(tion_fan_speed).publish_state(x.custom_fan_mode.has_value() ? *x.custom_fan_mode.value().c_str() - '0' : 0);"
      - lambda: "id(tion_heating).publish_state(x.action == climate::CLIMATE_ACTION_HEATING);"

sensor:
  - platform: template
    id: tion_fan_speed
    name: Fan Speed
binary_sensor:
  - platform: template
    id: tion_heating
    name: Heating
```

**Comment by dentra** [comment]
а вообще обогрев так виден:
<img width="570" alt="Снимок экрана 2024-01-18 в 17 46 50" src="https://github.com/dentra/esphome-tion/assets/8806059/001bfdf5-ee95-47ba-a6e7-a9f1a10bb0da">

**Comment by man55** [comment]
Спасибо. С состоянием обогревателя понял.
Фан спид заработал, только отображает почему-то с десятичным знаком
<img width="247" alt="image" src="https://github.com/dentra/esphome-tion/assets/30772900/84b12034-5fb3-4730-a5aa-019afd42ff16">

**Comment by dentra** [comment]
добавьте в сенсор accuracy_decimal: 0 или измените точность прямо в HA, так же можете изменить иконку:
```yaml
sensor:
  - platform: template
    id: tion_fan_speed
    name: Fan Speed
    accuracy_decimal: 0 
    icon: mdi:fan
binary_sensor:
  - platform: template
    id: tion_heating
    name: Heating
    icon: mdi:heat-wave
```
