### ISSUE TITLE
Несколько  бризеров на одной плате ESP32

### ISSUE THREAD

**Issue by Dexter-Lucky** [dentra/esphome-tion#29]
Добрый день!
У меня есть три бризера, два Lite и один 4S. Пытаюсь завести их в ХА через одну плату ESP32.
Не пойму, как завести несколько устройств на одну плату.
Скорректировал код следующим образом:
```
substitutions:
  # tion mac address. setup yours.
   #1 4S Гостинная:
  tion1_mac_address: FC:51:8F:F7:77:20
   #2 Lite Спальня:
  tion2_mac_address: C5:D4:AA:B8:FB:09
   #3 Lite Детская:
  tion3_mac_address: FA:24:0D:17:58:FC
  # name of the node.
  node_name: tion
  # name for main climate entity and prefix for all others.
  friendly_name: Бризеры
  # add suffix for node name to have one firmware for many devices.
  node_add_mac_suffix: "true"


packages:
  tion:
    url: https://github.com/dentra/esphome-tion
    ref: 2024.1.3 # cant use substitutions here
    files:
      ## Enable additional WiFi signal sensor. Comment next line to disable.
      - packages/wifi_signal.yaml
      ## Enable additional BLE RSSI sensor. Comment next line to disable.
      - packages/rssi_signal.yaml
      ## Enable additional Uptime sensor. Comment next line to disable.
      - packages/uptime.yaml
      ## Enable additional Restart button. Comment next line to disable.
      - packages/restart.yaml
      ## Base climate definition. Do not comment or move or remove.
      - packages/tion_4s_climate.yaml
      - packages/tion_lt_climate.yaml
      ## Enable maximum target temperature to 30°C. Comment next line to disable.
      - packages/tion_temperature30c.yaml
      ## Enable heat_cool mode to workaraund when using Home Assistant turn_on service.
      # - packages/tion_enable_heat_cool.yaml
      ## Uncomment next line to enable additional energy sensor.
      - packages/tion_energy.yaml
      ## Common configuration settings. Do not comment or move or remove.
      - packages/base.yaml
      ## BLE configuration settings. Do not comment or move or remove.
      - packages/esp32_ble.yaml
      ## Uncomment next line to enable persistent connection runtime control switch.
      #- packages/persistent.yaml
      ## Uncomment next line to enable additional connect switch useful for debugging.
      # - packages/connect.yaml
      ## Uncomment next line to enable additional internal timers support.
      - packages/tion_4s_timers.yaml
      ## Uncomment next line to enable monitor internal ESP temperature.
      - packages/esp32_temperature.yaml
      ## Uncomment next line to enable additional debug information.
      # - packages/debug.yaml



# Virtual port configuration
vport:
  - platform: tion_4s
    id: tion1_ble_vport
    ble_client_id: tion1_ble_client
    ## Optional, Do not disconnect after receiving state. Default: false.
    persistent_connection: false
    ## Optional, Allow to disable other BLE device scanning when breezer is already connected. Default: false.
    # disable_scan: false
    ## Optional, Interval between sending commmands. Set to 0ms to send one command per loop.
    # command_interval: 100ms
    ## Optional, Command queue size. Default: 10.
    # command_queue_size: 16
  - platform: tion_lt
    id: tion2_ble_vport
    ble_client_id: tion2_ble_client
    ## Optional, Do not disconnect after receiving state. Default: false.
    persistent_connection: false
    ## Optional, Allow to disable other BLE device scanning when breezer is already connected. Default: false.
    # disable_scan: false
    ## Optional, Interval between sending commmands. Set to 0ms to send one command per loop.
    # command_interval: 100ms
    ## Optional, Command queue size. Default: 10.
    # command_queue_size: 16
  - platform: tion_lt
    id: tion3_ble_vport
    ble_client_id: tion3_ble_client
    ## Optional, Do not disconnect after receiving state. Default: false.
    persistent_connection: false
    ## Optional, Allow to disable other BLE device scanning when breezer is already connected. Default: false.
    # disable_scan: false
    ## Optional, Interval between sending commmands. Set to 0ms to send one command per loop.
    # command_interval: 100ms
    ## Optional, Command queue size. Default: 10.
    # command_queue_size: 16

# Main climate component configuration.
climate:
  - id: !extend tion_climate
    # Required, the name of climate entity
    name: Бризер Гостинная # use friendly_name
    # Optional, virtual port id. Default: autodetect
    vport_id: tion1_ble_vport
    # Optional, Temperatire of air before heater, °C (celsius).
    outdoor_temperature:
      name: "Outdoor Temperature"
    # Optional, Buzzer control switch.
    buzzer:
      name: "Buzzer"
    # Optional, Led control switch.
    led:
      name: "Led"
    # Optional, Heater power, W (watt).
    heater_power:
      name: "Heater power"
    # Optional, Total airflow counter, m³ (cubic meters).
    airflow_counter:
      name: "Airflow counter"
    # Optional, Recirculation control switch.
    recirculation:
      name: "Recirculation"
    # Optional, Current productivity, m³/h (cubic meters per hour).
    productivity:
      name: "Productivity"
    # Optional, Filter time left counter, days.
    filter_time_left:
      name: "Filter Time Left"
    # Optional, Filter warning state.
    filter_warnout:
      name: "Filter Warnout"
    # Optional, Tion firmware version.
    version:
      name: "Version"

    presets:
      # enable "home" preset and override default settings
      home: { fan_speed: 2, target_temperature: 10, gate_position: outdoor, mode: fan_only }
      # enable "away" preset with default settings
      away:
      # enable "boost" preset with default settings
      boost:
      # enable "sleep" preset and override default settings
      sleep: { fan_speed: 1, target_temperature: 10, gate_position: outdoor, mode: fan_only }
    # Optional, configure boost time
    boost_time:
      name: "Boost Time"
    # Optional, display remaining boost time
    boost_time_left:
      name: "Boost Time Left"
    # Optional, How often query device state. Default: 60s.
    update_interval: 60s
    # Optional, reset filter button
    reset_filter:
      name: "Reset Filter"
    # Optional, reset filter confirmation. When off then reset_filter will not work.
    reset_filter_confirm:
      name: "Reset Filter Confirm"
    # Optional, Informs about get state problem from breezer.
    state_warnout:
      name: "State Warnout"
    # Optional, Timeout when state_warnout will be informed. Default: 3s.
    state_timeout: 3s
    # Optional, Timeout to combine update operations. Default: 200ms.
    batch_timeout: 200ms
    # Optional, Reports Tion's errors (EC) and warnings (WS).
    errors:
      name: "Errors"
  - id: !extend tion_climate
    # Required, the name of climate entity
    name: Бризер Спальня # use friendly_name
    # Optional, virtual port id. Default: autodetect
    vport_id: tion2_ble_vport
    # Optional, Temperatire of air before heater, °C (celsius).
    outdoor_temperature:
      name: "Outdoor Temperature"
    # Optional, Buzzer control switch.
    buzzer:
      name: "Buzzer"
    # Optional, Heater power, W (watt).
    heater_power:
      name: "Heater power"
    # Optional, Total airflow counter, m³ (cubic meters).
    airflow_counter:
      name: "Airflow counter"
    # Optional, Gate state control binary sensor.
    gate_state:
      name: "Gate State"
    # Optional, Current productivity, m³/h (cubic meters per hour).
    productivity:
      name: "Productivity"
    # Optional, Filter time left counter, days.
    filter_time_left:
      name: "Filter Time Left"
    # Optional, Filter warning state.
    filter_warnout:
      name: "Filter Warnout"
    # Optional, Tion firmware version.
    version:
      name: "Version"

    presets:
      # enable "home" preset and override default settings
      home: { fan_speed: 2, target_temperature: 10, gate_position: outdoor, mode: fan_only }
      # enable "away" preset with default settings
      away:
      # enable "boost" preset with default settings
      boost:
      # enable "sleep" preset and override default settings
      sleep: { fan_speed: 1, target_temperature: 10, gate_position: outdoor, mode: fan_only }
    # Optional, configure boost time
    boost_time:
      name: "Boost Time"
    # Optional, display remaining boost time
    boost_time_left:
      name: "Boost Time Left"
    # Optional, How often query device state. Default: 60s.
    update_interval: 60s
    # Optional, reset filter button
    reset_filter:
      name: "Reset Filter"
    # Optional, reset filter confirmation. When off then reset_filter will not work.
    reset_filter_confirm:
      name: "Reset Filter Confirm"
    # Optional, Informs about get state problem from breezer.
    state_warnout:
      name: "State Warnout"
    # Optional, Timeout when state_warnout will be informed. Default: 3s.
    state_timeout: 3s
    # Optional, Timeout to combine update operations. Default: 200ms.
    batch_timeout: 200ms
    # Optional, Reports Tion's errors (EC) and warnings (WS).
    errors:
      name: "Errors"
  - id: !extend tion_climate
    # Required, the name of climate entity
    name: Бризер Детская # use friendly_name
    # Optional, virtual port id. Default: autodetect
    vport_id: tion3_ble_vport
    # Optional, Temperatire of air before heater, °C (celsius).
    outdoor_temperature:
      name: "Outdoor Temperature"
    # Optional, Buzzer control switch.
    buzzer:
      name: "Buzzer"
    # Optional, Heater power, W (watt).
    heater_power:
      name: "Heater power"
    # Optional, Total airflow counter, m³ (cubic meters).
    airflow_counter:
      name: "Airflow counter"
    # Optional, Gate state control binary sensor.
    gate_state:
      name: "Gate State"
    # Optional, Current productivity, m³/h (cubic meters per hour).
    productivity:
      name: "Productivity"
    # Optional, Filter time left counter, days.
    filter_time_left:
      name: "Filter Time Left"
    # Optional, Filter warning state.
    filter_warnout:
      name: "Filter Warnout"
    # Optional, Tion firmware version.
    version:
      name: "Version"

    presets:
      # enable "home" preset and override default settings
      home: { fan_speed: 2, target_temperature: 10, gate_position: outdoor, mode: fan_only }
      # enable "away" preset with default settings
      away:
      # enable "boost" preset with default settings
      boost:
      # enable "sleep" preset and override default settings
      sleep: { fan_speed: 1, target_temperature: 10, gate_position: outdoor, mode: fan_only }
    # Optional, configure boost time
    boost_time:
      name: "Boost Time"
    # Optional, display remaining boost time
    boost_time_left:
      name: "Boost Time Left"
    # Optional, How often query device state. Default: 60s.
    update_interval: 60s
    # Optional, reset filter button
    reset_filter:
      name: "Reset Filter"
    # Optional, reset filter confirmation. When off then reset_filter will not work.
    reset_filter_confirm:
      name: "Reset Filter Confirm"
    # Optional, Informs about get state problem from breezer.
    state_warnout:
      name: "State Warnout"
    # Optional, Timeout when state_warnout will be informed. Default: 3s.
    state_timeout: 3s
    # Optional, Timeout to combine update operations. Default: 200ms.
    batch_timeout: 200ms
    # Optional, Reports Tion's errors (EC) and warnings (WS).
    errors:
      name: "Errors"
```

Но при проверке выдает ошибку:

```
INFO ESPHome 2024.4.0
INFO Reading configuration /config/esphome/breezers.yaml...
WARNING Found '$tion_mac_address' (see sensor->1->mac_address) which looks like a substitution, but 'tion_mac_address' was not declared
WARNING Found '$tion_mac_address' (see ble_client->mac_address) which looks like a substitution, but 'tion_mac_address' was not declared
WARNING Found '$tion_mac_address' (see sensor->1->mac_address) which looks like a substitution, but 'tion_mac_address' was not declared
WARNING Found '$tion_mac_address' (see ble_client->mac_address) which looks like a substitution, but 'tion_mac_address' was not declared
INFO Detected timezone 'Europe/Moscow'
Failed config

sensor.ble_rssi: [source /data/packages/a28f4a62/packages/rssi_signal.yaml:2]
  platform: ble_rssi
  
  MAC Address must consist of 6 : (colon) separated parts.
  mac_address: $tion_mac_address
  name: RSSI
  filters: 
    throttle_average: 60s
  entity_category: diagnostic
climate.tion_lt: [source /data/packages/a28f4a62/packages/tion_lt_climate.yaml:2]
  platform: tion_lt
  id: tion_climate
  heater_power: 
    id: heater_power
    on_raw_value: 
      then: 
        lambda: id(heater_power_plus_fan).update();
    name: Heater power
  name: Бризер Детская
  vport_id: tion3_ble_vport
  outdoor_temperature: 
    name: Outdoor Temperature
  buzzer: 
    name: Buzzer
  led: 
    name: Led
  airflow_counter: 
    name: Airflow counter
  
  [recirculation] is an invalid option for [climate.tion_lt]. Please check the indentation.
  recirculation: 
    name: Recirculation
  productivity: 
    name: Productivity
  filter_time_left: 
    name: Filter Time Left
  filter_warnout: 
    name: Filter Warnout
  version: 
    name: Version
  presets: 
    home: 
      fan_speed: 2
      target_temperature: 10
      gate_position: outdoor
      mode: fan_only
    away: 
    boost: 
    sleep: 
      fan_speed: 1
      target_temperature: 10
      gate_position: outdoor
      mode: fan_only
  boost_time: 
    name: Boost Time
  boost_time_left: 
    name: Boost Time Left
  update_interval: 60s
  reset_filter: 
    name: Reset Filter
  reset_filter_confirm: 
    name: Reset Filter Confirm
  state_warnout: 
    name: State Warnout
  state_timeout: 3s
  batch_timeout: 200ms
  errors: 
    name: Errors
  gate_state: 
    name: Gate State
ble_client: [source /data/packages/a28f4a62/packages/esp32_ble.yaml:22]
  - 
    MAC Address must consist of 6 : (colon) separated parts.
    mac_address: $tion_mac_address
    id: tion_ble_client
```

Как я понимаю, в других файлах отсутствуют такие переменные, как **tion1_mac_address** и т.д., а есть только **tion_mac_address**.
Как от этого уйти - не понял.
Подскажите, как решить эту задачу.
Заранее, спасибо!
