### ISSUE TITLE
fatal error: esphome/components/ota/ota_component.h: No such file or directory

### ISSUE THREAD

**Issue by hertznsk** [dentra/esphome-tion#36]
После одного из обновлений ESPHome стала возникать ошибка.

По сравнению с примером конфигурации <https://github.com/dentra/esphome-tion/blob/2024.1.3/tion-4s-uart.yaml> были добавлены директивы ota чтобы иметь возможность обновлять по сети. Ранее это не вызывало проблем.

Можно ли с этим что-то сделать?

ESPHome `2024.6.4`

Конфигурация:

```yaml
#
# https://github.com/dentra/esphome-tion
#

substitutions:
  # name of the node.
  node_name: tion-4s
  # name for main climate entity and prefix for all others.
  friendly_name: $node_name
  # add suffix for node name to have one firmware for many devices.
  node_add_mac_suffix: "false"

packages:
  tion:
    url: https://github.com/dentra/esphome-tion
    ref: 2024.1.3 # cant use substitutions here
    files:
      ## Enable additional WiFi signal sensor. Comment next line to disable.
      - packages/wifi_signal.yaml
      ## Enable additional Uptime sensor. Comment next line to disable.
      - packages/uptime.yaml
      ## Enable additional Restart button. Comment next line to disable.
      - packages/restart.yaml
      ## Base climate definition. Do not comment or move or remove.
      - packages/tion_4s_climate.yaml
      ## Enable maximum target temperature to 30°C. Comment next line to disable.
      - packages/tion_temperature30c.yaml
      ## Enable heat_cool mode to workaraund when using Home Assistant turn_on service.
      # - packages/tion_enable_heat_cool.yaml
      ## Uncomment next line to enable additional energy sensor.
      - packages/tion_energy.yaml
      ## Common configuration settings. Do not comment or move or remove.
      - packages/base.yaml
      # change to esp32_s2.yaml/esp32_c3.yaml to use with ESP32-S2/ESP32-C3 chip or change to esp32.yaml to use with ESP32 chip.
      - packages/esp32_s3.yaml
      ## Uncomment next line to enable additional internal timers support.
      # - packages/tion_4s_timers.yaml
      ## Uncomment next line to enable monitor internal ESP temperature.
      - packages/esp32_temperature.yaml
      ## Uncomment next line to enable additional debug information.
      # - packages/debug.yaml

# Uncomment to enable MQTT connecion.
# WARNINIG: If you leave next api section for logging purpose
#           and do not use Home Assistant, you need to uncomment
#           reboot_timeout parameter.
# mqtt:
#   broker: !secret mqtt_borker
#   port: !secret mqtt_port
#   username: !secret mqtt_username
#   password: !secret mqtt_password

# Enable Home Assistant API connection. Please do not remove to keep logs functioning.
api:
  # Uncomment next line if you do not use Home Assistant.
  #reboot_timeout: 0s
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_passw

# WiFi hotspot configuration.
# Comment next 3 lines to enable manual WiFi conviguration via access point.
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # напрямую подключаться к сети без предварительного сканирования (нужно т.к. сеть скрытая)
  fast_connect: true
  domain: .mydomain.ru
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Tion-4S Fallback Hotspot"
    password: !secret fallback_passw

# Virtual port configuration
vport:
  - platform: tion_4s_uart
    id: tion_uart_vport
    uart_id: uart_tion
    ## Optional, Interval between sending commmands. Set to 0ms to send one command per loop.
    # command_interval: 20ms
    ## Optional, Command queue size. Default: 10.
    # command_queue_size: 16
    ## Optional, Interval between sending heartbeat commands. Default: 5s.
    # heartbeat_interval: 5s

# Main climate component configuration.
climate:
  - id: !extend tion_climate
    # Required, the name of climate entity
    name: None # use friendly_name
    # Optional, virtual port id. Default: autodetect
    vport_id: tion_uart_vport
    # Optional, Temperatire of air before heater, °C (celsius).
    outdoor_temperature:
      name: "Outdoor Temperature"
    # Optional, Buzzer control switch.
    buzzer:
      name: "Buzzer"
    # Optional, Led control switch.
    led:
      name: "Led"
    # Optional, Heater power, W (watt).
    heater_power:
      name: "Heater power"
    # Optional, Total airflow counter, m³ (cubic meters).
    #airflow_counter:
    #  name: "Airflow counter"
    # Optional, Recirculation control switch.
    recirculation:
      name: "Recirculation"
    # Optional, Current productivity, m³/h (cubic meters per hour).
    productivity:
      name: "Productivity"
    # Optional, Filter time left counter, days.
    filter_time_left:
      name: "Filter Time Left"
    # Optional, Filter warning state.
    filter_warnout:
      name: "Filter Warnout"
    # Optional, Tion firmware version.
    version:
      name: "Version"
    # Optional, Enable presets. Default: <empty> (no presets)
    # Available configurable presets: home, away, boost, comfort, eco, sleep, activity.
    # Defaults:
    #   home    : { fan_speed: 2, target_temperature: 20, gate_position: auto, mode: heat }
    #   away    : { fan_speed: 1, target_temperature: 10, gate_position: auto, mode: fan_only }
    #   boost   : { fan_speed: 6, target_temperature: 10, gate_position: auto, mode: fan_only }
    #   comfort : { fan_speed: 2, target_temperature: 23, gate_position: auto, mode: heat }
    #   eco     : { fan_speed: 1, target_temperature: 16, gate_position: auto, mode: heat }
    #   sleep   : { fan_speed: 1, target_temperature: 18, gate_position: auto, mode: heat }
    #   activity: { fan_speed: 3, target_temperature: 18, gate_position: auto, mode: heat }
    # Boost is a special preset that runs for a period defined by boost_time and then switches back to the previous preset.
    # Available mode:
    #  * off - define but disable preset
    #  * heat - enable heater
    #  * fan_only - fan only
    # Available gate_position (this option is optional):
    #  * auto - use current gate position
    #  * outdoor - set gate position to outdoor air intake (3S and 4S only)
    #  * indoor - set gate position to indoor air intake (3S and 4S only)
    #  * mixed - set gate position to mixed air intake (3S only)
    presets:
      # enable "home" preset and override default settings
      home: { fan_speed: 2, target_temperature: 16, gate_position: outdoor, mode: heat }
      # enable "away" preset with default settings
      away:
      # enable "boost" preset with default settings
      boost:
      # enable "sleep" preset and override default settings
      sleep: { fan_speed: 1, target_temperature: 18, gate_position: outdoor, mode: heat }
    # Optional, configure boost time
    boost_time:
      name: "Boost Time"
    # Optional, display remaining boost time
    boost_time_left:
      name: "Boost Time Left"
    # Optional, How often query device state. Default: 60s.
    update_interval: 30s
    # Optional, reset filter button
    reset_filter:
      name: "Reset Filter"
    # Optional, reset filter confirmation. When off then reset_filter will not work.
    reset_filter_confirm:
      name: "Reset Filter Confirm"
    # Optional, Informs about get state problem from breezer.
    state_warnout:
      name: "State Warnout"
    # Optional, Timeout when state_warnout will be informed. Default: 3s.
    state_timeout: 3s
    # Optional, Timeout to combine update operations. Default: 200ms.
    batch_timeout: 200ms
    # Optional, Reports Tion's errors (EC) and warnings (WS).
    errors:
      name: "Errors"

## Uncomment if you plan to use decoded errors/warnings
#text_sensor:
#  - platform: template
#    id: tion_error_codes
#    name: "Error Codes"

## Uncomment if you plan to use reset errors/warnings functionality.
## This feature is experimental and may partially work or no work as expected.
#button:
#  - platform: template
#    name: "Reset Errors"
#    on_press:
#      - lambda: id(tion_climate).reset_errors();
```

Лог:

```text
INFO ESPHome 2024.6.4
INFO Reading configuration /config/esphome/tion-4s.yaml...
INFO Detected timezone 'Europe/Moscow'
INFO Generating C++ source...
INFO Compiling app...
Processing tion-4s (board: esp32-s3-devkitc-1; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
 - framework-espidf @ 3.40407.0 (4.4.7) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5 
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Generating assembly for certificate bundle...
Dependency Graph
|-- Embedded Template Library @ 20.35.8
|-- noise-c @ 0.1.4
Compiling .pioenvs/tion-4s/src/esphome/components/api/api_connection.o
Compiling .pioenvs/tion-4s/src/esphome/components/api/api_frame_helper.o
Compiling .pioenvs/tion-4s/src/esphome/components/api/api_pb2.o
Compiling .pioenvs/tion-4s/src/esphome/components/api/api_pb2_service.o
Compiling .pioenvs/tion-4s/src/esphome/components/api/api_server.o
Compiling .pioenvs/tion-4s/src/esphome/components/api/list_entities.o
Compiling .pioenvs/tion-4s/src/esphome/components/api/proto.o
Compiling .pioenvs/tion-4s/src/esphome/components/api/subscribe_state.o
Compiling .pioenvs/tion-4s/src/esphome/components/api/user_services.o
Compiling .pioenvs/tion-4s/src/esphome/components/binary_sensor/automation.o
Compiling .pioenvs/tion-4s/src/esphome/components/binary_sensor/binary_sensor.o
Compiling .pioenvs/tion-4s/src/esphome/components/binary_sensor/filter.o
Compiling .pioenvs/tion-4s/src/esphome/components/button/button.o
Compiling .pioenvs/tion-4s/src/esphome/components/captive_portal/captive_portal.o
Compiling .pioenvs/tion-4s/src/esphome/components/climate/climate.o
Compiling .pioenvs/tion-4s/src/esphome/components/climate/climate_mode.o
Compiling .pioenvs/tion-4s/src/esphome/components/climate/climate_traits.o
Compiling .pioenvs/tion-4s/src/esphome/components/esp32/core.o
Compiling .pioenvs/tion-4s/src/esphome/components/esp32/gpio.o
Compiling .pioenvs/tion-4s/src/esphome/components/esp32/preferences.o
Compiling .pioenvs/tion-4s/src/esphome/components/esp32_usb_dis/esp32_usb_dis.o
Compiling .pioenvs/tion-4s/src/esphome/components/esphome/ota/ota_esphome.o
Compiling .pioenvs/tion-4s/src/esphome/components/homeassistant/time/homeassistant_time.o
Compiling .pioenvs/tion-4s/src/esphome/components/internal_temperature/internal_temperature.o
Compiling .pioenvs/tion-4s/src/esphome/components/logger/logger.o
Compiling .pioenvs/tion-4s/src/esphome/components/logger/logger_esp32.o
Compiling .pioenvs/tion-4s/src/esphome/components/logger/logger_esp8266.o
Compiling .pioenvs/tion-4s/src/esphome/components/logger/logger_host.o
Compiling .pioenvs/tion-4s/src/esphome/components/logger/logger_libretiny.o
Compiling .pioenvs/tion-4s/src/esphome/components/logger/logger_rp2040.o
Compiling .pioenvs/tion-4s/src/esphome/components/md5/md5.o
Compiling .pioenvs/tion-4s/src/esphome/components/mdns/mdns_component.o
Compiling .pioenvs/tion-4s/src/esphome/components/mdns/mdns_esp32.o
Compiling .pioenvs/tion-4s/src/esphome/components/mdns/mdns_esp8266.o
Compiling .pioenvs/tion-4s/src/esphome/components/mdns/mdns_host.o
Compiling .pioenvs/tion-4s/src/esphome/components/mdns/mdns_libretiny.o
Compiling .pioenvs/tion-4s/src/esphome/components/mdns/mdns_rp2040.o
Compiling .pioenvs/tion-4s/src/esphome/components/network/util.o
Compiling .pioenvs/tion-4s/src/esphome/components/number/automation.o
Compiling .pioenvs/tion-4s/src/esphome/components/number/number.o
Compiling .pioenvs/tion-4s/src/esphome/components/number/number_call.o
Compiling .pioenvs/tion-4s/src/esphome/components/number/number_traits.o
Compiling .pioenvs/tion-4s/src/esphome/components/ota/ota_backend.o
Compiling .pioenvs/tion-4s/src/esphome/components/ota/ota_backend_arduino_esp32.o
Compiling .pioenvs/tion-4s/src/esphome/components/ota/ota_backend_arduino_esp8266.o
Compiling .pioenvs/tion-4s/src/esphome/components/ota/ota_backend_arduino_libretiny.o
Compiling .pioenvs/tion-4s/src/esphome/components/ota/ota_backend_arduino_rp2040.o
Compiling .pioenvs/tion-4s/src/esphome/components/ota/ota_backend_esp_idf.o
Compiling .pioenvs/tion-4s/src/esphome/components/restart/button/restart_button.o
Compiling .pioenvs/tion-4s/src/esphome/components/safe_mode/safe_mode.o
Compiling .pioenvs/tion-4s/src/esphome/components/select/select.o
Compiling .pioenvs/tion-4s/src/esphome/components/select/select_call.o
Compiling .pioenvs/tion-4s/src/esphome/components/select/select_traits.o
Compiling .pioenvs/tion-4s/src/esphome/components/sensor/automation.o
Compiling .pioenvs/tion-4s/src/esphome/components/sensor/filter.o
Compiling .pioenvs/tion-4s/src/esphome/components/sensor/sensor.o
Compiling .pioenvs/tion-4s/src/esphome/components/socket/bsd_sockets_impl.o
Compiling .pioenvs/tion-4s/src/esphome/components/socket/lwip_raw_tcp_impl.o
Compiling .pioenvs/tion-4s/src/esphome/components/socket/lwip_sockets_impl.o
Compiling .pioenvs/tion-4s/src/esphome/components/socket/socket.o
Compiling .pioenvs/tion-4s/src/esphome/components/switch/automation.o
Compiling .pioenvs/tion-4s/src/esphome/components/switch/switch.o
Compiling .pioenvs/tion-4s/src/esphome/components/template/sensor/template_sensor.o
Compiling .pioenvs/tion-4s/src/esphome/components/text_sensor/filter.o
Compiling .pioenvs/tion-4s/src/esphome/components/text_sensor/text_sensor.o
Compiling .pioenvs/tion-4s/src/esphome/components/time/automation.o
Compiling .pioenvs/tion-4s/src/esphome/components/time/real_time_clock.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion-api/crc.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion-api/log.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion-api/tion-api-3s.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion-api/tion-api-4s.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion-api/tion-api-ble-3s.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion-api/tion-api-ble-lt.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion-api/tion-api-lt.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion-api/tion-api-uart-3s.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion-api/tion-api-uart-4s.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion-api/tion-api.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion-api/utils.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion/tion.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion/tion_climate.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion/tion_climate_component.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion/tion_component.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion/tion_fan.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion/tion_fan_component.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion_4s/climate/tion_4s_climate.o
Compiling .pioenvs/tion-4s/src/esphome/components/tion_4s_uart/tion_4s_uart.o
src/esphome/components/tion_4s_uart/tion_4s_uart.cpp:4:10: fatal error: esphome/components/ota/ota_component.h: No such file or directory
 #include "esphome/components/ota/ota_component.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/tion-4s/src/esphome/components/tion_4s_uart/tion_4s_uart.o] Error 1
========================= [FAILED] Took 207.85 seconds =========================
```
