### ISSUE TITLE
2024.8.0 режим persistent не отображается уровень сигнала ble

### ISSUE THREAD

**Issue by tarikptz** [dentra/esphome-tion#39]
При включении режима persistent не отображается уровень сигнала ble. В обычном режиме работает.

**Comment by dentra** [comment]
попробуйте добавить в конфиг, в секцию `sensor`, например, в начало, чтобы получилось примерно так:
```yaml
sensor:
 - platform: ble_client
   type: rssi
   ble_client_id: tion_ble_client
   name: BLE RSSI
   entity_category: diagnostic
```
