### ISSUE TITLE
Тестирование на ESP32-C6

### ISSUE THREAD

**Issue by rvalitov** [dentra/esphome-tion#42]
Хочу потестировать на C6, вижу что в next ветке уже это есть.
Как лучше подключить next ветку?
Я хотел сделать вот так:
```yaml
packages:
  tion:
    url: https://github.com/dentra/esphome-tion
    ref: next # cant use substitutions here
```
Но к сожалению не работает. Вываливается ошибка `fetch-pack: invalid index-pack output` или клонируется ветка `master`.

**Comment by rvalitov** [comment]
Получилось решить проблему добавив `refresh: 0s`:
```yaml
packages:
  tion:
    url: https://github.com/dentra/esphome-tion
    ref: next # cant use substitutions here
    refresh: 0s
```

После этого всё догружается поэтапно.
