### ISSUE TITLE
Зачем нужно делать pin версии ESP-IDF?

### ISSUE THREAD

**Issue by rvalitov** [dentra/esphome-tion#43]
В файле `esp32_ble.yaml` жестко фиксируется версия:
```yaml
esp32:
  board: $board
  framework:
    type: esp-idf
    # eshhome 2023.12.x, version: 4.4.5 platform_version: 5.4.0
    # esphome 2024.5.x, version: 4.4.7, platform_version: 5.4.0
    # esp-idf 5.2.1,  version: 5.2.1, platform_version: 6.7.0
    version: 4.4.7 # pin esp-idf
```

Для чего это нужно? Для обычных устройств это лишь приводит к сообщению во время компиляции:
```
WARNING The selected ESP-IDF framework version is not the recommended one. If there are connectivity or build issues please remove the manual version.
```
Потому что нет согласованности между выбранной версией ESP-IDF и версией ESPHome. Я например использую версию ESPHome 2024.10.2 и логично было бы использовать ту версию, которая поставляется с ESPHome. 

Исключение составляют устройства типа ESP32-C6 и ESP32-H2 - им надо задавать версию ESP-IDF вручную, т.к. поддержка начинается с 5.1 и выше.
