### ISSUE TITLE
Подключение нескольких бризеров в последнем релизе

### ISSUE THREAD

**Issue by ebloved** [dentra/esphome-tion#53]
Доброго дня. 
Спасибо за прекрасную интеграцию!
Попытался настроить подключение одного Lite/4S с помощью последних примеров конфигурации, получил при компиляции ошибку переопределения ble_client_id
```
ble_client: [source /data/packages/23f42cf2/packages/esp32_ble.yaml:20]
  - mac_address: MY:MA:CA:DD:RE:SS
    id: tion_ble_client
    auto_connect: True
  - mac_address: MY:MA:CA:DD:RE:SS
    
    ID tion_ble_client redefined! Check ble_client->0->id.
    id: tion_ble_client
    auto_connect: True
```

Нашёл вот этот комментарий, по нему настроил подключение
https://github.com/dentra/esphome-tion/issues/7#issuecomment-1448576000

Текущая конфигурация, с которой всё работает:

```
substitutions:
  tion_kitchen_mac_address: MY:MA:CA:DD:RE:11
  tion_childroom_mac_address: MY:MA:CA:DD:RE:22
  tion_bedroom_mac_address: MY:MA:CA:DD:RE:33

  node_name: esp32-tion
  name: $node_name
  node_add_mac_suffix: "false"
  board: esp32dev
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  framework_type: arduino

  tion_version: 2022.10.1

esphome:
  name: $node_name
  name_add_mac_suffix: $node_add_mac_suffix
  project:
    name: "dentra.tion"
    version: "$tion_version ($framework_type)"
  min_version: 2022.12.8

api:
  encryption:
    key: "key"

ota:
  - platform: esphome
    password: "password"


esp32:
  board: $board
  framework:
    type: $framework_type

preferences:
  flash_write_interval: 10min

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "$name Fallback Hotspot"

logger:

esp32_ble_tracker:

external_components:
  - source: github://dentra/esphome-components@2023.2.0
    components: [crash_info, etl, otax, vport, esp32_usb_dis]
  - source: github://dentra/esphome-tion@$tion_version

ble_client:
  - mac_address: $tion_kitchen_mac_address
    id: tion1_ble_client
  - mac_address: $tion_childroom_mac_address
    id: tion2_ble_client
  - mac_address: $tion_bedroom_mac_address
    id: tion3_ble_client

vport:
  - platform: tion_ble
    id: tion1_ble_vport
    ble_client_id: tion1_ble_client
    update_interval: 60s
    persistent_connection: false
    state_timeout: 15s
    disable_scan: false

  - platform: tion_ble
    id: tion2_ble_vport
    ble_client_id: tion2_ble_client
    update_interval: 60s
    persistent_connection: false
    state_timeout: 15s
    disable_scan: false

  - platform: tion_ble
    id: tion3_ble_vport
    ble_client_id: tion3_ble_client
    update_interval: 60s
    persistent_connection: false
    state_timeout: 15s
    disable_scan: false

climate:
  - platform: tion_lt
    vport_id: tion1_ble_vport
    name: "Tion Kitchen"
    buzzer:
      name: "Tion Kitchen Buzzer"
    led:
      name: "Tion Kitchen Led"
    outdoor_temperature:
      name: "Tion Kitchen Outdoor Temperature"
    heater_power:
      name: "Tion Kitchen Heater power"
    airflow_counter:
      name: "Tion Kitchen Airflow counter"
    filter_time_left:
      name: "Tion Kitchen Filter Time Left"
    filter_warnout:
      name: "Tion Kitchen Filter Warnout"
    version:
      name: "Tion Kitchen Version"
    presets:
      home: { fan_speed: 2, target_temperature: 16, mode: fan_only }
      away:
      boost:
      sleep: { fan_speed: 1, target_temperature: 18, mode: fan_only }
    boost_time:
      name: $name Boost Time
    boost_time_left:
      name: $name Boost Time Left

  - platform: tion_lt
    vport_id: tion2_ble_vport
    name: "Tion 2"
    Конфиг такой же, как и для Tion Kitchen


  - platform: tion_4s
    vport_id: tion3_ble_vport
    name: "Tion Bedroom"
    buzzer:
      name: "Tion Bedroom Buzzer"
    led:
      name: "Tion Bedroom Led"
    outdoor_temperature:
      name: "Tion Bedroom Outdoor Temperature"
    heater_power:
      name: "Tion Bedroom Heater power"
    airflow_counter:
      name: "Tion Bedroom Airflow counter"
    filter_time_left:
      name: "Tion Bedroom Filter Time Left"
    filter_warnout:
      name: "Tion Bedroom Filter Warnout"
    version:
      name: "Tion Bedroom Version"
    presets:
      home: { fan_speed: 2, target_temperature: 16, mode: fan_only }
      away:
      boost:
      sleep: { fan_speed: 1, target_temperature: 18, mode: fan_only }
    boost_time:
      name: Tion Bedroom Boost Time
    boost_time_left:
      name: Tion Bedroom Boost Time Left
```
Но, насколько я понимаю, это старый релиз и в нём нет функции Auto.

Подскажите, пожалуйста, что мне необходимо поправить в конфигурации, чтобы подключить три бризера по BLE в последней прошивке?

Спасибо!

**Comment by bazuchan** [comment]
У меня вот так работает
```
substitutions:
  node_name: tion5
  friendly_name: $node_name
  tion_conn: ble
  board: lolin32_lite
  board_code: $board
  mac1: CF:E3:A3:FB:50:B3
  mac2: CD:6A:89:0F:B1:0E

esp32:
  board: $board
  framework:
    type: esp-idf
    version: 4.4.7
    platform_version: 5.4.0

wifi:
  ap: !remove
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_pass
    on_begin:
      then:
        lambda: |-
          id(tion_ble_client1).set_enabled(false);
          id(tion_ble_client2).set_enabled(false);

logger:

packages:
  tion:
    url: https://github.com/dentra/esphome-tion
    ref: 2024.12.0 # cant use substitutions here
    files:
      - packages/wifi_signal.yaml
      - packages/uptime.yaml
      - packages/restart.yaml
      - packages/base.yaml
      - packages/tion_lt.yaml

esp32_ble_tracker:
  id: tion_esp32_ble_tracker

ble_client:
  - mac_address: ${mac1}
    id: tion_ble_client1
  - mac_address: ${mac2}
    id: tion_ble_client2

vport:
  - platform: tion_lt_ble
    id: tion_ble_vport1
    ble_client_id: tion_ble_client1
    persistent_connection: false
  - platform: tion_lt_ble
    id: tion_ble_vport2
    ble_client_id: tion_ble_client2
    persistent_connection: false

tion:
  - type: lt
    id: tion_api1
    vport_id: tion_ble_vport1
    update_interval: 60s
    batch_timeout: 200ms
    state_timeout: 30s
    force_update: false
  - type: lt
    id: tion_api2
    vport_id: tion_ble_vport2
    update_interval: 60s
    batch_timeout: 200ms
    state_timeout: 30s
    force_update: false

climate:
  - platform: tion
    id: tion_climate1
    tion_id: tion_api1
    name: $node_name breezer1
    enable_heat_cool: True
  - platform: tion
    id: tion_climate2
    tion_id: tion_api2
    name: $node_name breezer2
    enable_heat_cool: True

sensor:
  - platform: tion
    id: tion_outdoor_temperature1
    tion_id: tion_api1
    type: outdoor_temperature
    name: Outdoor Temperature1
  - platform: tion
    tion_id: tion_api2
    id: tion_outdoor_temperature2
    type: outdoor_temperature
    name: Outdoor Temperature2
  - platform: tion
    id: tion_heater_power1
    tion_id: tion_api1
    type: heater_power
    name: Heater power1
  - platform: tion
    id: tion_heater_power2
    tion_id: tion_api2
    type: heater_power
    name: Heater power2
  - platform: tion
    id: tion_filter_time_left_days1
    tion_id: tion_api1
    type: filter_time_left_days
    name: Filter Time Left1
  - platform: tion
    id: tion_filter_time_left_days2
    tion_id: tion_api2
    type: filter_time_left_days
    name: Filter Time Left2
  - platform: ble_rssi
    id: tion_ble_rssi1
    mac_address: $mac1
    name: RSSI1
    filters:
      throttle_average: 60s
    entity_category: diagnostic
  - platform: ble_rssi
    id: tion_ble_rssi2
    mac_address: $mac2
    name: RSSI2
    filters:
      throttle_average: 60s
    entity_category: diagnostic

binary_sensor:
  - platform: tion
    id: tion_state_problem1
    tion_id: tion_api1
    type: state
    name: State Problem1
  - platform: tion
    id: tion_state_problem2
    tion_id: tion_api2
    type: state
    name: State Problem2

text_sensor:
  - platform: tion
    id: tion_firmware_version1
    tion_id: tion_api1
    type: firmware_version
    name: Version1
  - platform: tion
    id: tion_firmware_version2
    tion_id: tion_api2
    type: firmware_version
    name: Version2
  - platform: tion
    id: tion_errors1
    tion_id: tion_api1
    type: errors
    name: Errors1
  - platform: tion
    id: tion_errors2
    tion_id: tion_api2
    type: errors
    name: Errors2

button:
  - platform: tion
    id: tion_reset_filter1
    tion_id: tion_api1
    type: reset_filter
    name: Reset Filter1
    confirm:
      name: Reset Filter Confirm
  - platform: tion
    id: tion_reset_filter2
    tion_id: tion_api2
    type: reset_filter
    name: Reset Filter2
    confirm:
      name: Reset Filter Confirm
```
